services:

  # Main Application Container
  partify-ecommerce:
    build:
      context: .
      dockerfile: src/Partify.UI/Dockerfile
    depends_on: 
     - postgres-db
    ports:
     - "5010:8080"  
     - "5011:8081"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://+:8081
        - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=../../certs/aspnetapp.pfx
        - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=DevCert123#
        - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://+:8080
        - DB_HOST=postgres-db
        - DB_PORT=5432
        - REDIS_PORT=6379
        - REDIS_HOST=redis
        - DB_USER=postgres
        - DB_NAME=PartifyEcommerceDb
        - DB_PASSWORD=admin
    volumes:
        - ./certs:/certs:ro
    networks:
        - internal-network

  # Postgres Database Container
  postgres-db:
    image: postgres:latest
    environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=postgres
        - POSTGRES_DB=PartifyEcommerceDb
    volumes:
        - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
        - "5998:5432"
    networks:
        - internal-network

    # Redis Cache
  redis: 
    image: redis:latest
    volumes:
        - ./src/redis-cache:/data 
    ports:
        - "6379:6379"
    networks:
        - internal-network

# Networks
networks:
  internal-network:
    driver: bridge