--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-23 17:18:17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

-- CREATE SCHEMA public;


-- ALTER SCHEMA public OWNER TO pg_database_owner;

-- --
-- -- TOC entry 4995 (class 0 OID 0)
-- -- Dependencies: 4
-- -- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
-- --

-- COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 240 (class 1259 OID 16922)
-- Name: Addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Addresses" (
    "Id" integer NOT NULL,
    "Place" text NOT NULL,
    "UserId" uuid,
    "Street" text NOT NULL,
    "HouseNumber" text NOT NULL,
    "PostalCity" text NOT NULL,
    "PostalCode" text NOT NULL,
    "CountryId" integer NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Addresses" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16921)
-- Name: Addresses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Addresses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Addresses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16835)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16834)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16788)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16848)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16847)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16860)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16872)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16887)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16795)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" uuid NOT NULL,
    "FirstName" text NOT NULL,
    "Surname" text NOT NULL,
    "NIP" text,
    "Title" text,
    "IsActive" boolean NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16940)
-- Name: CartItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CartItems" (
    "Id" integer NOT NULL,
    "CartId" integer NOT NULL,
    "OfferId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."CartItems" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16939)
-- Name: CartItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CartItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CartItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16900)
-- Name: Carts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Carts" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "TotalCartValue" numeric(10,2),
    "MinimalDeliveryValue" numeric(10,2),
    "TotalItemsValue" numeric(10,2),
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Carts" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16899)
-- Name: Carts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Carts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Carts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16803)
-- Name: Conditions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Conditions" (
    "Id" integer NOT NULL,
    "ConditionTitle" text NOT NULL,
    "ConditionDescription" text NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Conditions" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16802)
-- Name: Conditions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Conditions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Conditions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16811)
-- Name: Countries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Countries" (
    "Id" integer NOT NULL,
    "CountryName" text NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Countries" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16810)
-- Name: Countries_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Countries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Countries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16819)
-- Name: DeliveryTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DeliveryTypes" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."DeliveryTypes" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16818)
-- Name: DeliveryTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DeliveryTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DeliveryTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 16956)
-- Name: LikedOffers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LikedOffers" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "OfferId" integer NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."LikedOffers" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16955)
-- Name: LikedOffers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LikedOffers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LikedOffers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16972)
-- Name: OfferDeliveryTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OfferDeliveryTypes" (
    "Id" integer NOT NULL,
    "OfferId" integer NOT NULL,
    "DeliveryTypeId" integer NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."OfferDeliveryTypes" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16971)
-- Name: OfferDeliveryTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OfferDeliveryTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OfferDeliveryTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16911)
-- Name: Offers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Offers" (
    "Id" integer NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "StockQuantity" integer NOT NULL,
    "IsOfferPrivate" boolean NOT NULL,
    "SellerId" uuid NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Offers" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16910)
-- Name: Offers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Offers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Offers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16827)
-- Name: ProductCategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductCategories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CategoryImage" text NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."ProductCategories" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16826)
-- Name: ProductCategories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductCategories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductCategories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 17011)
-- Name: ProductImages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductImages" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "ImagePath" text NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."ProductImages" OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17010)
-- Name: ProductImages_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductImages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductImages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 16988)
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "ProductName" text NOT NULL,
    "OfferId" integer NOT NULL,
    "Description" text NOT NULL,
    "ProductCategoryId" integer NOT NULL,
    "ConditionId" integer NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateEdited" timestamp with time zone,
    "DateDeleted" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 16987)
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16783)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4979 (class 0 OID 16922)
-- Dependencies: 240
-- Data for Name: Addresses; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Addresses" ("Id", "Place", "UserId", "Street", "HouseNumber", "PostalCity", "PostalCode", "CountryId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 'Jasienna', '01997205-ae88-78c4-9eb3-fb70080dca4b', 'Jasienna', '15', 'Korzenna', '33-322', 1, '2025-09-22 19:36:39.2015+02', NULL, NULL, true);


--
-- TOC entry 4968 (class 0 OID 16835)
-- Dependencies: 229
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4957 (class 0 OID 16788)
-- Dependencies: 218
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES ('01997205-af5f-7360-95f7-a67f1e936203', 'User', 'USER', NULL);
INSERT INTO public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES ('af639c37-8849-4aab-8c57-fd2d26e1be0c', 'Admin', 'ADMIN', NULL);


--
-- TOC entry 4970 (class 0 OID 16848)
-- Dependencies: 231
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4971 (class 0 OID 16860)
-- Dependencies: 232
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4972 (class 0 OID 16872)
-- Dependencies: 233
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES ('01997205-ae88-78c4-9eb3-fb70080dca4b', 'af639c37-8849-4aab-8c57-fd2d26e1be0c');
INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES ('019976ff-6aff-7b3f-8340-0b9239ed1b3b', '01997205-af5f-7360-95f7-a67f1e936203');


--
-- TOC entry 4973 (class 0 OID 16887)
-- Dependencies: 234
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4958 (class 0 OID 16795)
-- Dependencies: 219
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUsers" ("Id", "FirstName", "Surname", "NIP", "Title", "IsActive", "DateCreated", "DateEdited", "DateDeleted", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('01997205-ae88-78c4-9eb3-fb70080dca4b', 'Jan', 'Kowalski', NULL, NULL, true, '2025-09-22 17:23:18.935236+02', '2025-09-23 16:16:37.524925+02', NULL, 'jankowalski12@gmail.com', 'JANKOWALSKI12@GMAIL.COM', 'jankowalski12@gmail.com', 'JANKOWALSKI12@GMAIL.COM', true, 'AQAAAAIAAYagAAAAEN1luukWPazXzrZTPrZ6a2UeI1ULydoRvGGkHDrhqW1xyUsYMxrKiEeU+Trk/BrU8g==', 'FFPCKFHE5XHDTBXNMXQC7ILMFJDS6G35', '0df11bbc-58b9-4542-a5df-9eb6f55e16f0', '694202137', false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "FirstName", "Surname", "NIP", "Title", "IsActive", "DateCreated", "DateEdited", "DateDeleted", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('019976ff-6aff-7b3f-8340-0b9239ed1b3b', 'Jan', 'Nowak', NULL, NULL, true, '2025-09-23 16:34:34.539217+02', NULL, NULL, 'jannowak12@gmail.com', 'JANNOWAK12@GMAIL.COM', 'jannowak12@gmail.com', 'JANNOWAK12@GMAIL.COM', false, 'AQAAAAIAAYagAAAAEPNCJ0uKJRDtV6aaiBHMI+XPHXSyHW3evNSHOoP8DnxU0UIQOEcZ5Sd4BTamAo6pIg==', 'PAABJFVDM42BODARDJLRLKREW6BO65NX', '825f7914-9b26-4784-877a-971c73a07c56', NULL, false, false, NULL, true, 0);


--
-- TOC entry 4981 (class 0 OID 16940)
-- Dependencies: 242
-- Data for Name: CartItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."CartItems" ("Id", "CartId", "OfferId", "Quantity", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 2, 7, 9, '2025-09-23 16:34:39.932652+02', NULL, '2025-09-23 16:34:57.317257+02', false);
INSERT INTO public."CartItems" ("Id", "CartId", "OfferId", "Quantity", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, 2, 10, 1, '2025-09-23 16:34:43.608907+02', NULL, '2025-09-23 16:34:57.679921+02', false);
INSERT INTO public."CartItems" ("Id", "CartId", "OfferId", "Quantity", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (3, 2, 11, 1, '2025-09-23 16:34:44.102993+02', NULL, '2025-09-23 16:34:57.944481+02', false);
INSERT INTO public."CartItems" ("Id", "CartId", "OfferId", "Quantity", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (4, 2, 12, 1, '2025-09-23 16:34:44.686302+02', NULL, '2025-09-23 16:34:58.189584+02', false);
INSERT INTO public."CartItems" ("Id", "CartId", "OfferId", "Quantity", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (5, 2, 13, 1, '2025-09-23 16:34:45.402855+02', NULL, '2025-09-23 16:34:58.440749+02', false);
INSERT INTO public."CartItems" ("Id", "CartId", "OfferId", "Quantity", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (6, 2, 14, 4, '2025-09-23 16:34:47.119207+02', NULL, '2025-09-23 16:34:58.755858+02', false);


--
-- TOC entry 4975 (class 0 OID 16900)
-- Dependencies: 236
-- Data for Name: Carts; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Carts" ("Id", "UserId", "TotalCartValue", "MinimalDeliveryValue", "TotalItemsValue", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, '01997205-ae88-78c4-9eb3-fb70080dca4b', NULL, NULL, NULL, '2025-09-22 17:23:18.934816+02', NULL, NULL, true);
INSERT INTO public."Carts" ("Id", "UserId", "TotalCartValue", "MinimalDeliveryValue", "TotalItemsValue", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, '019976ff-6aff-7b3f-8340-0b9239ed1b3b', 1017.00, 17.00, 1000.00, '2025-09-23 16:34:34.538966+02', NULL, NULL, true);


--
-- TOC entry 4960 (class 0 OID 16803)
-- Dependencies: 221
-- Data for Name: Conditions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Conditions" ("Id", "ConditionTitle", "ConditionDescription", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 'New', 'Never opened, never used', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."Conditions" ("Id", "ConditionTitle", "ConditionDescription", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, 'Used', 'Used, visible use marks', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."Conditions" ("Id", "ConditionTitle", "ConditionDescription", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (3, 'Broken', 'Doesn''t work, for parts', '2025-04-08 00:00:00+02', NULL, NULL, true);


--
-- TOC entry 4962 (class 0 OID 16811)
-- Dependencies: 223
-- Data for Name: Countries; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Countries" ("Id", "CountryName", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 'Poland', '2025-12-12 00:00:00+01', NULL, NULL, true);


--
-- TOC entry 4964 (class 0 OID 16819)
-- Dependencies: 225
-- Data for Name: DeliveryTypes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."DeliveryTypes" ("Id", "Title", "Description", "Price", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 'Inpost Parcel Locker - S', 'For small items like cpu, ram', 15.00, '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."DeliveryTypes" ("Id", "Title", "Description", "Price", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, 'Inpost Parcel Locker - M', 'For medium things like laptop', 17.00, '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."DeliveryTypes" ("Id", "Title", "Description", "Price", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (3, 'Inpost Parcel Locker - B', 'For big stuff like PC case', 20.00, '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."DeliveryTypes" ("Id", "Title", "Description", "Price", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (4, 'DPD Courier', '', 24.99, '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."DeliveryTypes" ("Id", "Title", "Description", "Price", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (5, 'Inpost Courier', '', 24.99, '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."DeliveryTypes" ("Id", "Title", "Description", "Price", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (6, 'UPS Courier', '', 24.99, '2025-04-08 00:00:00+02', NULL, NULL, true);


--
-- TOC entry 4983 (class 0 OID 16956)
-- Dependencies: 244
-- Data for Name: LikedOffers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4985 (class 0 OID 16972)
-- Dependencies: 246
-- Data for Name: OfferDeliveryTypes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 6, 1, '2025-09-22 19:52:16.461083+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, 6, 4, '2025-09-22 19:52:16.474577+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (3, 7, 1, '2025-09-23 16:18:13.246618+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (4, 7, 4, '2025-09-23 16:18:13.257854+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (5, 7, 5, '2025-09-23 16:18:13.258233+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (6, 7, 6, '2025-09-23 16:18:13.258277+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (15, 8, 3, '2025-09-23 16:19:27.256731+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (16, 8, 4, '2025-09-23 16:19:27.256842+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (17, 8, 5, '2025-09-23 16:19:27.256871+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (18, 8, 6, '2025-09-23 16:19:27.256894+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (19, 9, 2, '2025-09-23 16:20:52.141842+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (20, 9, 5, '2025-09-23 16:20:52.141914+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (21, 9, 6, '2025-09-23 16:20:52.141936+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (22, 10, 1, '2025-09-23 16:22:31.490647+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (23, 10, 4, '2025-09-23 16:22:31.490716+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (24, 10, 6, '2025-09-23 16:22:31.490744+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (25, 11, 2, '2025-09-23 16:24:52.232228+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (26, 11, 6, '2025-09-23 16:24:52.232311+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (27, 12, 2, '2025-09-23 16:28:33.128005+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (28, 12, 5, '2025-09-23 16:28:33.131836+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (29, 13, 1, '2025-09-23 16:30:45.560828+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (30, 13, 5, '2025-09-23 16:30:45.561036+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (31, 13, 6, '2025-09-23 16:30:45.561108+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (32, 14, 2, '2025-09-23 16:32:49.713056+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (33, 14, 4, '2025-09-23 16:32:49.713132+02', NULL, NULL, true);
INSERT INTO public."OfferDeliveryTypes" ("Id", "OfferId", "DeliveryTypeId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (34, 14, 6, '2025-09-23 16:32:49.713189+02', NULL, NULL, true);


--
-- TOC entry 4977 (class 0 OID 16911)
-- Dependencies: 238
-- Data for Name: Offers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (6, 12.00, 2, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-22 19:52:16.396326+02', NULL, '2025-09-22 19:52:22.045271+02', false);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (7, 799.00, 20, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:18:13.191372+02', NULL, NULL, true);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (8, 2500.00, 2, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:19:18.547887+02', NULL, NULL, true);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (9, 300.00, 1, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:20:52.140562+02', NULL, NULL, true);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (10, 230.00, 1, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:22:31.489647+02', NULL, NULL, true);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (11, 500.00, 50, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:24:52.230714+02', NULL, NULL, true);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (12, 50.00, 100, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:28:33.094884+02', NULL, NULL, true);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (13, 600.00, 20, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:30:45.559818+02', NULL, NULL, true);
INSERT INTO public."Offers" ("Id", "Price", "StockQuantity", "IsOfferPrivate", "SellerId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (14, 250.00, 4, false, '01997205-ae88-78c4-9eb3-fb70080dca4b', '2025-09-23 16:32:49.711552+02', NULL, NULL, true);


--
-- TOC entry 4966 (class 0 OID 16827)
-- Dependencies: 227
-- Data for Name: ProductCategories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 'GPU', 'Graphical Processing Unit', '/category-images/gpu.png', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, 'CPU', 'Central Processing Unit', '/category-images/cpu.png', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (3, 'RAM', 'Random Access Memory', '/category-images/ram.png', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (4, 'HDD', 'Hard Drive', '/category-images/hdd.png', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (5, 'SSD', 'Solid State Drive', '/category-images/ssd.png', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (6, 'PC Case', 'Home for your pc parts', '/category-images/case.png', '2025-04-08 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (7, 'PSU', '', '/category-images/psu.png', '2025-04-12 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (8, 'FAN', '', '/category-images/fan.png', '2025-04-12 00:00:00+02', NULL, NULL, true);
INSERT INTO public."ProductCategories" ("Id", "Name", "Description", "CategoryImage", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (10, 'Phone', '', '/category-images/phone.png', '2025-04-12 00:00:00+02', NULL, NULL, true);


--
-- TOC entry 4989 (class 0 OID 17011)
-- Dependencies: 250
-- Data for Name: ProductImages; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 1, '/offer-images/z_6b935f1b-6351-40cd-b01c-3b67273e9386.png', '2025-09-22 19:52:16.460402+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, 2, '/offer-images/ryzen_a22b9b3a-a97a-4b11-9015-bac97747497a.jpg', '2025-09-23 16:18:13.245868+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (3, 3, '/offer-images/radeon2_30ba251b-c6ff-4fd6-8f79-9931a5c8f0a9.jpg', '2025-09-23 16:19:18.549081+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (4, 4, '/offer-images/msi-motherboard_4dca3e42-6d90-4334-a6bc-8dff52e482da.jpg', '2025-09-23 16:20:52.141836+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (5, 5, '/offer-images/gskill_353506db-d48d-4c04-a167-c2eb78a28dae.jpg', '2025-09-23 16:22:31.490642+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (6, 6, '/offer-images/br-11134207-7r98o-lxryqmcacvy73d_c3431e16-5a1b-4c7a-b970-a35ecbf2ccd8.jpg', '2025-09-23 16:24:52.232222+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (7, 7, '/offer-images/purewin2_8ba978a1-b27c-45c5-a514-e4e446de5ebb.jpg', '2025-09-23 16:28:33.127205+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (8, 7, '/offer-images/purewing_138475d7-995e-4c9a-b36e-8e5fc078d240.jpg', '2025-09-23 16:28:33.127227+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (9, 8, '/offer-images/9080_be126315-54ca-4941-b86f-82a06a9550aa.jpg', '2025-09-23 16:30:45.560791+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (10, 9, '/offer-images/1_71679d95-5adf-4eb2-a69c-cd5c8715c5a2.jpg', '2025-09-23 16:32:49.713049+02', NULL, NULL, true);
INSERT INTO public."ProductImages" ("Id", "ProductId", "ImagePath", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (11, 9, '/offer-images/2_d7cad344-d7a8-4ba9-af78-45bd49ea3d67.jpg', '2025-09-23 16:32:49.71305+02', NULL, NULL, true);


--
-- TOC entry 4987 (class 0 OID 16988)
-- Dependencies: 248
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (1, 'asdas', 6, 'asd', 2, 2, '2025-09-22 19:52:16.436024+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (2, 'Ryzen 7 5700X3D', 7, '🔥 Unleash Elite Performance – AMD Ryzen 7 5700X3D 🔥 Experience next-level computing with the Ryzen 7 5700X3D, engineered for gamers, creators, and power users who demand maximum performance. Featuring AMD’s cutting-edge 3D V-Cache™ technology, this 8-core, 16-thread processor delivers exceptional speed, responsiveness, and multitasking capabilities.

⚙️ Key Features:

3D V-Cache™ for up to 96MB L3 cache – massive boost in gaming and productivity workloads

8 cores / 16 threads – seamless multitasking and high-performance computing

Base Clock: 3.0 GHz | Boost Clock: Up to 4.1 GHz

Socket AM4 – compatible with a wide range of motherboards

Unlocked for overclocking – push your system to the limit

🎮 Whether you''re dominating in AAA titles or rendering high-res content, the Ryzen 5700X3D offers unmatched efficiency and power.

🛒 Limited-time offer – grab yours now and elevate your rig with one of AMD’s most advanced desktop processors!', 2, 1, '2025-09-23 16:18:13.222813+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (3, 'Radeon 7900XT 20GB GDDR6', 8, '🚀 Power Beyond Limits – AMD Radeon RX 7900 XT 🚀 Step into the future of gaming and content creation with the Radeon RX 7900 XT, built on AMD’s revolutionary RDNA™ 3 architecture. Designed for ultra-high performance, this graphics card delivers stunning visuals, lightning-fast frame rates, and next-gen features that redefine what your PC can do.

🎯 Key Highlights:

20GB GDDR6 memory – massive bandwidth for 4K gaming and heavy workloads

RDNA™ 3 architecture – enhanced efficiency and performance per watt

DisplayPort™ 2.1 support – future-ready for high refresh rate 4K and 8K displays

Ray tracing & AI acceleration – immersive lighting, shadows, and smarter rendering

PCIe 4.0 interface – blazing-fast data transfer for peak responsiveness

🎮 Whether you''re chasing ultra settings in AAA titles or building complex 3D scenes, the RX 7900 XT delivers uncompromising power and fidelity.

💥 Special Offer – Upgrade your setup today and dominate your digital world with AMD’s elite GPU!', 1, 1, '2025-09-23 16:19:18.548087+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (4, 'MSI x470 Gaming Plus MAX', 9, '🎮 MSI X470 Gaming Plus Max – Built for Power, Tuned for Performance 🎮 Level up your rig with the MSI X470 Gaming Plus Max, a high-performance AM4 motherboard designed for gamers and PC enthusiasts who demand stability, speed, and style. Whether you''re pairing it with a Ryzen 5000 series CPU or building a sleek gaming setup, this board delivers rock-solid reliability and advanced features at a great value.

🧩 Core Features:

Supports AMD Ryzen 1000–5000 series processors – future-ready with BIOS Flashback support

DDR4 Boost – optimized memory performance up to 4133 MHz (OC)

PCIe Steel Armor – reinforced slots for heavy GPUs

Audio Boost – immersive sound with studio-grade quality

Extended heatsink design – enhanced thermal dissipation for sustained performance

Mystic Light RGB – customizable lighting to match your build’s vibe

🔧 Ideal for gamers, streamers, and creators looking for a reliable backbone for their AM4 system. With its sleek black-and-red design and gamer-focused layout, the X470 Gaming Plus Max is ready to dominate.

💥 Limited-time offer – grab yours now and build your dream PC with MSI’s trusted performance!', 6, 2, '2025-09-23 16:20:52.140664+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (5, 'GSkill 32GB (2x16GB) 3600MHZ CL18', 10, '⚡️ G.SKILL Ripjaws V 32GB DDR4 3600MHz – Speed Meets Stability ⚡️ Upgrade your system with the G.SKILL Ripjaws V Series, engineered for high-performance gaming, multitasking, and content creation. This 32GB kit (2x16GB) delivers blazing-fast speeds and rock-solid reliability, making it the perfect choice for Ryzen and Intel platforms alike.

🧠 Key Specs:

Capacity: 32GB (2x16GB)

Speed: DDR4-3600MHz

Latency: CL18 / CL16 (varies by model)

Voltage: 1.35V – optimized for performance and efficiency

XMP 2.0 support – easy one-click overclocking

Stylish heat spreader – sleek design with effective thermal dissipation

🎮 Whether you''re gaming at ultra settings or running demanding applications, this memory kit keeps your system responsive and smooth.

💥 Hot Deal – Boost your rig’s performance today with G.SKILL’s trusted speed and quality!', 3, 2, '2025-09-23 16:22:31.489761+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (6, 'Xeon 2680 v4 + MOBO + RAM 16GB ', 11, '🛠️ Ultimate Budget Workstation Kit – Xeon E5-2680 v4 + Machinist m-ATX + 16GB Killsire DDR4 🛠️ Build a powerful and cost-effective workstation with this all-in-one Xeon performance kit, perfect for gamers, creators, and productivity enthusiasts who want serious multi-core muscle without breaking the bank.

⚙️ Kit Includes:

Intel Xeon E5-2680 v4 – 14 cores / 28 threads, turbo up to 3.3GHz, ideal for multitasking, rendering, and virtualization

Machinist m-ATX Motherboard – compact and efficient, supports DDR4, SATA, M.2, and PCIe for flexible builds

Killsire 16GB DDR4 (2x8GB) – fast and reliable memory for smooth multitasking and gaming

💡 Why Choose This Kit?

Excellent value for high-core-count performance

Great for budget gaming, streaming, and workstation tasks

Compatible with most mATX cases and standard components

Plug-and-play setup with pre-tested compatibility

🔥', 2, 1, '2025-09-23 16:24:52.230807+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (7, 'BeQuiet! Pure Wings 120mm', 12, '🌬️ be quiet! Pure Wings 2 120mm – Whisper-Quiet Cooling, German Precision 🌬️ Keep your system cool and silent with the Pure Wings 2 120mm fan from be quiet!, renowned for its ultra-low noise levels and reliable performance. Whether you''re building a gaming rig or upgrading your airflow, this fan delivers exceptional cooling with near-silent operation.

🛠️ Key Features:

Low noise level – only 19.2 dBA at max speed

Airflow-optimized fan blades – improved cooling and reduced turbulence

Long-life rifle bearing – up to 80,000 hours of operation

Ideal for case and radiator use – versatile mounting options

German-engineered quality – trusted by PC builders worldwide

💡 Perfect for silent builds, media centers, and airflow upgrades without the noise.

🎯 Special Offer – Upgrade your cooling with Pure Wings 2 and enjoy peace of mind with quiet efficiency!', 8, 1, '2025-09-23 16:28:33.11652+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (8, 'Samsung 980 PRO 2TB', 13, '⚡️ Samsung 980 PRO 2TB NVMe SSD – Blazing Speed, Elite Reliability ⚡️ Unlock ultra-fast storage performance with the Samsung 980 PRO 2TB, built for gamers, creators, and professionals who demand top-tier speed and endurance. Powered by PCIe Gen4 and Samsung’s in-house controller, this SSD delivers lightning-fast read/write speeds and rock-solid reliability.

🚀 Key Features:

Capacity: 2TB – ample space for games, media, and heavy workloads

Interface: PCIe Gen4 x4 NVMe 1.3c – next-gen bandwidth for peak performance

Read Speed: Up to 7,000 MB/s | Write Speed: Up to 5,100 MB/s

Form Factor: M.2 2280 – fits most modern desktops and laptops

Samsung Magician Software – easy drive management and performance optimization

Advanced thermal control – nickel-coated controller and heat spreader for sustained speed

💡 Ideal for 4K video editing, high-end gaming, and data-intensive applications.

🔥 Special Offer – Supercharge your system with Samsung’s flagship SSD and experience the future of storage today!', 5, 1, '2025-09-23 16:30:45.559983+02', NULL, NULL, true);
INSERT INTO public."Products" ("Id", "ProductName", "OfferId", "Description", "ProductCategoryId", "ConditionId", "DateCreated", "DateEdited", "DateDeleted", "IsActive") VALUES (9, 'Segate FireCuda 2TB', 14, '🗄️ 2TB HDD – Reliable Storage for Everyday Needs 🗄️ Expand your system’s capacity with a 2TB Hard Disk Drive, perfect for storing large files, backups, media libraries, and more. Whether you''re building a budget PC, upgrading an older system, or adding mass storage to your setup, this drive offers dependable performance at an affordable price.

🔧 Key Features:

Capacity: 2TB – ideal for documents, games, videos, and backups

Interface: SATA III (6Gb/s) – fast and widely compatible

Speed: 5400–7200 RPM (varies by model) – balance between performance and efficiency

Cache: Up to 256MB – smoother data access and transfer

Form Factor: 3.5" – fits standard desktop drive bays

MTBF: Up to 1 million hours – long-term reliability

💡 Great for bulk storage, media servers, and secondary drives in gaming or workstation builds.

🎯 Special Offer – Get dependable storage with a 2TB HDD and keep your data safe and accessible!', 4, 2, '2025-09-23 16:32:49.711644+02', NULL, NULL, true);


--
-- TOC entry 4956 (class 0 OID 16783)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20250922144600_InitailPostgressMigrationm', '9.0.9');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20250922144636_InitialPostgressMigration', '9.0.9');


--
-- TOC entry 4996 (class 0 OID 0)
-- Dependencies: 239
-- Name: Addresses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Addresses_Id_seq"', 1, true);


--
-- TOC entry 4997 (class 0 OID 0)
-- Dependencies: 228
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 4998 (class 0 OID 0)
-- Dependencies: 230
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 4999 (class 0 OID 0)
-- Dependencies: 241
-- Name: CartItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CartItems_Id_seq"', 6, true);


--
-- TOC entry 5000 (class 0 OID 0)
-- Dependencies: 235
-- Name: Carts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Carts_Id_seq"', 2, true);


--
-- TOC entry 5001 (class 0 OID 0)
-- Dependencies: 220
-- Name: Conditions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Conditions_Id_seq"', 1, false);


--
-- TOC entry 5002 (class 0 OID 0)
-- Dependencies: 222
-- Name: Countries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Countries_Id_seq"', 1, false);


--
-- TOC entry 5003 (class 0 OID 0)
-- Dependencies: 224
-- Name: DeliveryTypes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."DeliveryTypes_Id_seq"', 1, false);


--
-- TOC entry 5004 (class 0 OID 0)
-- Dependencies: 243
-- Name: LikedOffers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LikedOffers_Id_seq"', 1, false);


--
-- TOC entry 5005 (class 0 OID 0)
-- Dependencies: 245
-- Name: OfferDeliveryTypes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OfferDeliveryTypes_Id_seq"', 34, true);


--
-- TOC entry 5006 (class 0 OID 0)
-- Dependencies: 237
-- Name: Offers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Offers_Id_seq"', 14, true);


--
-- TOC entry 5007 (class 0 OID 0)
-- Dependencies: 226
-- Name: ProductCategories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductCategories_Id_seq"', 1, false);


--
-- TOC entry 5008 (class 0 OID 0)
-- Dependencies: 249
-- Name: ProductImages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductImages_Id_seq"', 11, true);


--
-- TOC entry 5009 (class 0 OID 0)
-- Dependencies: 247
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 9, true);


--
-- TOC entry 4770 (class 2606 OID 16928)
-- Name: Addresses PK_Addresses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id");


--
-- TOC entry 4749 (class 2606 OID 16841)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4733 (class 2606 OID 16794)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 4752 (class 2606 OID 16854)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4755 (class 2606 OID 16866)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 4758 (class 2606 OID 16876)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 4760 (class 2606 OID 16893)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 4737 (class 2606 OID 16801)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 4774 (class 2606 OID 16944)
-- Name: CartItems PK_CartItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id");


--
-- TOC entry 4763 (class 2606 OID 16904)
-- Name: Carts PK_Carts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Carts"
    ADD CONSTRAINT "PK_Carts" PRIMARY KEY ("Id");


--
-- TOC entry 4740 (class 2606 OID 16809)
-- Name: Conditions PK_Conditions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Conditions"
    ADD CONSTRAINT "PK_Conditions" PRIMARY KEY ("Id");


--
-- TOC entry 4742 (class 2606 OID 16817)
-- Name: Countries PK_Countries; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Countries"
    ADD CONSTRAINT "PK_Countries" PRIMARY KEY ("Id");


--
-- TOC entry 4744 (class 2606 OID 16825)
-- Name: DeliveryTypes PK_DeliveryTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DeliveryTypes"
    ADD CONSTRAINT "PK_DeliveryTypes" PRIMARY KEY ("Id");


--
-- TOC entry 4778 (class 2606 OID 16960)
-- Name: LikedOffers PK_LikedOffers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LikedOffers"
    ADD CONSTRAINT "PK_LikedOffers" PRIMARY KEY ("Id");


--
-- TOC entry 4782 (class 2606 OID 16976)
-- Name: OfferDeliveryTypes PK_OfferDeliveryTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferDeliveryTypes"
    ADD CONSTRAINT "PK_OfferDeliveryTypes" PRIMARY KEY ("Id");


--
-- TOC entry 4766 (class 2606 OID 16915)
-- Name: Offers PK_Offers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Offers"
    ADD CONSTRAINT "PK_Offers" PRIMARY KEY ("Id");


--
-- TOC entry 4746 (class 2606 OID 16833)
-- Name: ProductCategories PK_ProductCategories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductCategories"
    ADD CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id");


--
-- TOC entry 4790 (class 2606 OID 17017)
-- Name: ProductImages PK_ProductImages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductImages"
    ADD CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id");


--
-- TOC entry 4787 (class 2606 OID 16994)
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- TOC entry 4731 (class 2606 OID 16787)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4735 (class 1259 OID 17030)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 4767 (class 1259 OID 17023)
-- Name: IX_Addresses_CountryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Addresses_CountryId" ON public."Addresses" USING btree ("CountryId");


--
-- TOC entry 4768 (class 1259 OID 17024)
-- Name: IX_Addresses_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Addresses_UserId" ON public."Addresses" USING btree ("UserId");


--
-- TOC entry 4747 (class 1259 OID 17025)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 4750 (class 1259 OID 17027)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 4753 (class 1259 OID 17028)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 4756 (class 1259 OID 17029)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 4771 (class 1259 OID 17032)
-- Name: IX_CartItems_CartId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CartItems_CartId" ON public."CartItems" USING btree ("CartId");


--
-- TOC entry 4772 (class 1259 OID 17033)
-- Name: IX_CartItems_OfferId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CartItems_OfferId" ON public."CartItems" USING btree ("OfferId");


--
-- TOC entry 4761 (class 1259 OID 17034)
-- Name: IX_Carts_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Carts_UserId" ON public."Carts" USING btree ("UserId");


--
-- TOC entry 4775 (class 1259 OID 17035)
-- Name: IX_LikedOffers_OfferId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LikedOffers_OfferId" ON public."LikedOffers" USING btree ("OfferId");


--
-- TOC entry 4776 (class 1259 OID 17036)
-- Name: IX_LikedOffers_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LikedOffers_UserId" ON public."LikedOffers" USING btree ("UserId");


--
-- TOC entry 4779 (class 1259 OID 17037)
-- Name: IX_OfferDeliveryTypes_DeliveryTypeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OfferDeliveryTypes_DeliveryTypeId" ON public."OfferDeliveryTypes" USING btree ("DeliveryTypeId");


--
-- TOC entry 4780 (class 1259 OID 17038)
-- Name: IX_OfferDeliveryTypes_OfferId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OfferDeliveryTypes_OfferId" ON public."OfferDeliveryTypes" USING btree ("OfferId");


--
-- TOC entry 4764 (class 1259 OID 17039)
-- Name: IX_Offers_SellerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Offers_SellerId" ON public."Offers" USING btree ("SellerId");


--
-- TOC entry 4788 (class 1259 OID 17040)
-- Name: IX_ProductImages_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductImages_ProductId" ON public."ProductImages" USING btree ("ProductId");


--
-- TOC entry 4783 (class 1259 OID 17041)
-- Name: IX_Products_ConditionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Products_ConditionId" ON public."Products" USING btree ("ConditionId");


--
-- TOC entry 4784 (class 1259 OID 17042)
-- Name: IX_Products_OfferId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Products_OfferId" ON public."Products" USING btree ("OfferId");


--
-- TOC entry 4785 (class 1259 OID 17043)
-- Name: IX_Products_ProductCategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Products_ProductCategoryId" ON public."Products" USING btree ("ProductCategoryId");


--
-- TOC entry 4734 (class 1259 OID 17026)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 4738 (class 1259 OID 17031)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 4799 (class 2606 OID 16929)
-- Name: Addresses FK_Addresses_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 4800 (class 2606 OID 16934)
-- Name: Addresses FK_Addresses_Countries_CountryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("Id") ON DELETE CASCADE;


--
-- TOC entry 4791 (class 2606 OID 16842)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4792 (class 2606 OID 16855)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4793 (class 2606 OID 16867)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4794 (class 2606 OID 16877)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4795 (class 2606 OID 16882)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4796 (class 2606 OID 16894)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4801 (class 2606 OID 16945)
-- Name: CartItems FK_CartItems_Carts_CartId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES public."Carts"("Id") ON DELETE CASCADE;


--
-- TOC entry 4802 (class 2606 OID 16950)
-- Name: CartItems FK_CartItems_Offers_OfferId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES public."Offers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4797 (class 2606 OID 16905)
-- Name: Carts FK_Carts_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Carts"
    ADD CONSTRAINT "FK_Carts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4803 (class 2606 OID 16961)
-- Name: LikedOffers FK_LikedOffers_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LikedOffers"
    ADD CONSTRAINT "FK_LikedOffers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4804 (class 2606 OID 16966)
-- Name: LikedOffers FK_LikedOffers_Offers_OfferId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LikedOffers"
    ADD CONSTRAINT "FK_LikedOffers_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES public."Offers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4805 (class 2606 OID 16977)
-- Name: OfferDeliveryTypes FK_OfferDeliveryTypes_DeliveryTypes_DeliveryTypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferDeliveryTypes"
    ADD CONSTRAINT "FK_OfferDeliveryTypes_DeliveryTypes_DeliveryTypeId" FOREIGN KEY ("DeliveryTypeId") REFERENCES public."DeliveryTypes"("Id") ON DELETE CASCADE;


--
-- TOC entry 4806 (class 2606 OID 16982)
-- Name: OfferDeliveryTypes FK_OfferDeliveryTypes_Offers_OfferId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferDeliveryTypes"
    ADD CONSTRAINT "FK_OfferDeliveryTypes_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES public."Offers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4798 (class 2606 OID 16916)
-- Name: Offers FK_Offers_AspNetUsers_SellerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Offers"
    ADD CONSTRAINT "FK_Offers_AspNetUsers_SellerId" FOREIGN KEY ("SellerId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4810 (class 2606 OID 17018)
-- Name: ProductImages FK_ProductImages_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductImages"
    ADD CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- TOC entry 4807 (class 2606 OID 16995)
-- Name: Products FK_Products_Conditions_ConditionId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Conditions_ConditionId" FOREIGN KEY ("ConditionId") REFERENCES public."Conditions"("Id") ON DELETE CASCADE;


--
-- TOC entry 4808 (class 2606 OID 17000)
-- Name: Products FK_Products_Offers_OfferId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES public."Offers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4809 (class 2606 OID 17005)
-- Name: Products FK_Products_ProductCategories_ProductCategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_ProductCategories_ProductCategoryId" FOREIGN KEY ("ProductCategoryId") REFERENCES public."ProductCategories"("Id") ON DELETE CASCADE;


-- Completed on 2025-09-23 17:18:18

--
-- PostgreSQL database dump complete
--

